### ISSUE TITLE
Seems like "Set CPU Name String" doesn't work.

### ISSUE THREAD

**Issue by Aspector1** [clamchowder/MsrUtil#3]
I'm using R5 5600X

**Comment by Aspector1** [comment]
https://user-images.githubusercontent.com/84536195/198881907-4a2c68cd-6697-4bcd-9d93-9bb7db5f31a0.mp4

**Comment by AndreyRGW** [comment]
Same.

**Comment by clamchowder** [comment]
Whether it works seems to depend on the specific system, and possibly on what AGESA/BIOS version you have. 

Everything under the "Do not touch these buttons" area is for testing only and won't be supported, as they hit things other than performance counters (which is the primary purpose of the program). Readme explicitly says "They may or may not work and I generally recommend avoiding them unless you really know what you're doing."
